"""empty message

Revision ID: dfa754f5ee27
Revises: c59e8b89d123
Create Date: 2024-09-02 16:42:39.067073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa754f5ee27'
down_revision = 'c59e8b89d123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_birth_year_key', type_='unique')
        batch_op.drop_constraint('people_gender_key', type_='unique')
        batch_op.drop_constraint('people_mass_key', type_='unique')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_gravity_key', type_='unique')
        batch_op.drop_constraint('planets_population_key', type_='unique')
        batch_op.drop_constraint('planets_terrain_key', type_='unique')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('vehicles_cost_in_credits_key', type_='unique')
        batch_op.drop_constraint('vehicles_manufacturer_key', type_='unique')
        batch_op.drop_constraint('vehicles_model_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_unique_constraint('vehicles_model_key', ['model'])
        batch_op.create_unique_constraint('vehicles_manufacturer_key', ['manufacturer'])
        batch_op.create_unique_constraint('vehicles_cost_in_credits_key', ['cost_in_credits'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('planets_terrain_key', ['terrain'])
        batch_op.create_unique_constraint('planets_population_key', ['population'])
        batch_op.create_unique_constraint('planets_gravity_key', ['gravity'])

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_unique_constraint('people_mass_key', ['mass'])
        batch_op.create_unique_constraint('people_gender_key', ['gender'])
        batch_op.create_unique_constraint('people_birth_year_key', ['birth_year'])

    # ### end Alembic commands ###
